name: Build and Push Docker Image

on:
  push:
    tags:
      - '*'
  workflow_dispatch:

jobs:
  build-and-push:
    name: Build and Publish to Docker Hub
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
          ref: master

      - name: Get latest Git tag
        id: latest_tag
        run: |
          git fetch --tags --force
          latest_tag=$(git describe --tags --abbrev=0)
          version=${latest_tag#v}
          echo "Latest tag: $latest_tag"
          echo "Version without 'v' prefix: $version"
          echo "VERSION=$version" >> $GITHUB_ENV

      - name: Update version in src/version.ts
        run: sed -i "s/^export const version = .*;$/export const version = ${{ env.VERSION }};/" src/version.ts
  
      - name: Commit updated version file
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "noreply@github.com"
          git add src/version.ts
          git commit -m "bump bot version to ${{ env.VERSION }}"
          git push

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to Docker Hub
        uses: docker/login-action@v2.1.0
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and Push
        uses: docker/build-push-action@v4.0.0
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: tcortega/spear-bot:latest, tcortega/spear-bot:${{ env.VERSION }}